export default function Home() {
  return <>
    <a className="skip" href="#main">Skip to content</a>
    <header><a className="brand" href="#"><span className="monogram" aria-hidden="true">OF</span>Oscar Foxtrot<span className="legal">Pty Ltd</span></a><nav aria-label="Main navigation"><a href="#work">Our work</a><a href="#contact">Contact ↗</a></nav></header>
    <main id="main">
      <section className="hero"><p className="eyebrow">Independent software studio · Australia</p><h1>Small tools.<br/><span>Clear answers.</span></h1><div className="intro"><p>We build focused software that makes everyday work easier. Our current focus is practical tools for Salesforce administrators.</p><a className="button" href="#work">Explore our work <span aria-hidden="true">↓</span></a></div></section>
      <section id="work" className="work"><div className="section-label"><span>01 / Our work</span><span>Salesforce tools</span></div><div className="product"><div><span className="status">In development</span><h2>Picklist Doctor</h2><p className="lead">Understand why a picklist value isn’t available.</p><p>A read-only diagnostic tool that helps Salesforce administrators inspect picklist configuration, compare record types, and prepare a clear report of what they find.</p><p className="release">The initial build is running in a development org. Public installation and marketplace availability are not yet available.</p></div><div className="capabilities"><article><span>01</span><div><h3>Inspect configuration</h3><p>Explore accessible fields, values, and record types in the current user’s context.</p></div></article><article><span>02</span><div><h3>Compare record types</h3><p>See differences in available values, defaults, and controlling-value restrictions.</p></div></article><article><span>03</span><div><h3>Share the findings</h3><p>Copy a diagnostic report that distinguishes observed configuration from unknowns.</p></div></article></div></div></section>
      <section className="approach"><p className="eyebrow">How we build</p><h2>Useful by design.<br/>Honest about the limits.</h2><p>We favour focused tools, clear explanations, and careful access to data. Picklist Doctor reads configuration without changing CRM records. When the available metadata cannot explain a result, it says so.</p></section>
      <section id="contact" className="contact"><div><p className="eyebrow">Get in touch</p><h2>Questions about our work?</h2><p>Find our director, Don Nguyen, on GitHub.</p></div><a className="button" href="https://github.com/donnguyen-dev">Visit Don’s GitHub profile <span aria-hidden="true">↗</span></a></section>
    </main><footer><span>© {new Date().getFullYear()} Oscar Foxtrot Pty Ltd</span><span>Independent developer. No Salesforce affiliation or endorsement is claimed.</span></footer>
  </>;
}
